[".zprezto"]
	type = "git-repo"
	url = "https://github.com/sorin-ionescu/prezto.git"
	ezact = true
	refreshPeriod = "168h"
	[".zprezto".clone]
		args = ["--recurse-submodules"]
	[".zprezto".pull]
		args = ["--ff-only", "--recurse-submodules"]

[".config/iterm2/iterm2_shell_integration.zsh"]
	type = "file"
	url = "https://iterm2.com/shell_integration/zsh"
	exact = true

